minor deployment update pt.2

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -8,8 +8,14 @@ publish_to_pypi:
   tags:
     - shared_docker
   script:
+    - |
+      git fetch origin main
+      if ! git merge-base --is-ancestor $CI_COMMIT_SHA origin/main; then
+        echo "ERROR: This tag is not on the main branch. Aborting."
+        exit 1
+      fi
     - pip install build twine
     - python -m build
     - twine upload dist/*
   rules:
-     - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_TAG
+    - if: $CI_COMMIT_TAG =~ /^v/
